// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk0B7Dm5qVKclw2J33nbD0VQO5iXqaCyE',
    appId: '1:711686217205:web:899582bf6d594f5db094bc',
    messagingSenderId: '711686217205',
    projectId: 'tipu-order',
    authDomain: 'tipu-order.firebaseapp.com',
    storageBucket: 'tipu-order.firebasestorage.app',
    measurementId: 'G-8GWFYDYHXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR7gWvbnrRsqGkwDxbk3XDvoiOXRmr8Qc',
    appId: '1:711686217205:android:461be76f796e53d3b094bc',
    messagingSenderId: '711686217205',
    projectId: 'tipu-order',
    storageBucket: 'tipu-order.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8jr2rKSyR23IQWjAmJAg09d4g0wQxtPk',
    appId: '1:711686217205:ios:4eaf3c900afafda1b094bc',
    messagingSenderId: '711686217205',
    projectId: 'tipu-order',
    storageBucket: 'tipu-order.firebasestorage.app',
    iosBundleId: 'com.example.tipuOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8jr2rKSyR23IQWjAmJAg09d4g0wQxtPk',
    appId: '1:711686217205:ios:4eaf3c900afafda1b094bc',
    messagingSenderId: '711686217205',
    projectId: 'tipu-order',
    storageBucket: 'tipu-order.firebasestorage.app',
    iosBundleId: 'com.example.tipuOrderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk0B7Dm5qVKclw2J33nbD0VQO5iXqaCyE',
    appId: '1:711686217205:web:3d50cb7855b6de77b094bc',
    messagingSenderId: '711686217205',
    projectId: 'tipu-order',
    authDomain: 'tipu-order.firebaseapp.com',
    storageBucket: 'tipu-order.firebasestorage.app',
    measurementId: 'G-2XCH0S7GGY',
  );
}
